# Generated by Django 2.2.5 on 2021-04-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dreamentry',
            name='id',
        ),
        migrations.AlterField(
            model_name='dreamentry',
            name='dream',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
