# Generated by Django 3.1.6 on 2021-05-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dreamentry',
            name='id',
        ),
        migrations.AddField(
            model_name='dreamentry',
            name='bad_num',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dreamentry',
            name='good_num',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dreamentry',
            name='dream',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
