# Generated by Django 3.1.6 on 2021-05-31 08:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0002_auto_20210531_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamentry',
            name='id',
            field=models.AutoField(default=datetime.datetime(2021, 5, 31, 8, 47, 0, 456501, tzinfo=utc), primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dreamentry',
            name='dream',
            field=models.TextField(),
        ),
    ]
